source 'https://api.berkshelf.com'
group :integration do
  cookbook 'minitest-handler'
end

cookbook 'chruby'
cookbook 'yum-gina', git: 'git@github.com:gina-alaska/yum-gina-cookbook'
cookbook 'yum-epel'
cookbook 'unicorn'
cookbook 'nginx'
cookbook 'postgresql'
cookbook 'java'
cookbook 'memcached'
cookbook 'now'
cookbook 'magic_shell'

metadata
